"""add group_id to interaction_event

Revision ID: 3245945a5dc7
Revises: 65986c6727b3
Create Date: 2026-03-26 15:10:40.370918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3245945a5dc7'
down_revision = '65986c6727b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_event', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
