"""add student_record table

Revision ID: 3adff3973f49
Revises: 3245945a5dc7
Create Date: 2026-04-01 12:01:55.412082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adff3973f49'
down_revision = '3245945a5dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('student_canvas_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sortable_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dropped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_canvas_id', name='uq_student_record')
    )
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.create_index('ix_student_record_course_status', ['course_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.drop_index('ix_student_record_course_status')

    op.drop_table('student_record')
    # ### end Alembic commands ###
