"""add check_back_date table

Revision ID: 5caab3db83e2
Revises: 89a66f4e6d13
Create Date: 2026-03-17 06:46:21.956398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5caab3db83e2'
down_revision = '89a66f4e6d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_back_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('student_canvas_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_canvas_id', name='uq_check_back_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_back_date')
    # ### end Alembic commands ###
