"""add message_template table

Revision ID: 65986c6727b3
Revises: 1cd7c7a6c5c8
Create Date: 2026-03-25 19:14:31.971645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65986c6727b3'
down_revision = '1cd7c7a6c5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_template')
    # ### end Alembic commands ###
