"""add student_note table

Revision ID: 8534a2a73e7c
Revises: e65dc8804957
Create Date: 2026-03-05 09:05:22.753443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8534a2a73e7c'
down_revision = 'e65dc8804957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('student_canvas_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_canvas_id', name='uq_student_note')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_note')
    # ### end Alembic commands ###
