"""add canvas_cache table

Revision ID: d09191be1413
Revises: 
Create Date: 2026-02-28 11:01:49.100220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09191be1413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvas_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_cache_cache_key'), ['cache_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_cache_cache_key'))

    op.drop_table('canvas_cache')
    # ### end Alembic commands ###
