"""widen interaction_event unique constraint to include student

Revision ID: e65dc8804957
Revises: fb60959797d8
Create Date: 2026-02-28 11:18:40.416736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65dc8804957'
down_revision = 'fb60959797d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_interaction_event_type_source'), type_='unique')
        batch_op.create_unique_constraint('uq_interaction_event_type_source_student', ['event_type', 'source_id', 'student_canvas_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_event', schema=None) as batch_op:
        batch_op.drop_constraint('uq_interaction_event_type_source_student', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_interaction_event_type_source'), ['event_type', 'source_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
