"""add course_module table

Revision ID: e9530493c6cb
Revises: 3adff3973f49
Create Date: 2026-04-29 12:12:18.302444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9530493c6cb'
down_revision = '3adff3973f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('canvas_module_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'canvas_module_id', name='uq_course_module')
    )
    with op.batch_alter_table('course_module', schema=None) as batch_op:
        batch_op.create_index('ix_course_module_course_dates', ['course_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_module_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_module_course_id'))
        batch_op.drop_index('ix_course_module_course_dates')

    op.drop_table('course_module')
    # ### end Alembic commands ###
