"""add label and student_label tables

Revision ID: ed11b0f9566d
Revises: e9530493c6cb
Create Date: 2026-09-03 09:50:30.170398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed11b0f9566d'
down_revision = 'e9530493c6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('student_canvas_id', sa.BigInteger(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_canvas_id', 'label_id', name='uq_student_label')
    )
    with op.batch_alter_table('student_label', schema=None) as batch_op:
        batch_op.create_index('ix_student_label_course_student', ['course_id', 'student_canvas_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_label', schema=None) as batch_op:
        batch_op.drop_index('ix_student_label_course_student')

    op.drop_table('student_label')
    op.drop_table('label')
    # ### end Alembic commands ###
