"""add interaction_event table

Revision ID: fb60959797d8
Revises: d09191be1413
Create Date: 2026-02-28 11:10:22.087019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb60959797d8'
down_revision = 'd09191be1413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('student_canvas_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'source_id', name='uq_interaction_event_type_source')
    )
    with op.batch_alter_table('interaction_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_event_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interaction_event_student_canvas_id'), ['student_canvas_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_event_student_canvas_id'))
        batch_op.drop_index(batch_op.f('ix_interaction_event_course_id'))

    op.drop_table('interaction_event')
    # ### end Alembic commands ###
